### ISSUE TITLE
No scroll when configuring calendars

### ISSUE THREAD

**Issue by legigor** [butaji/Jump-in-Meeting#1]
I have there more calendars than can fit the window and I can't scroll/resize the window to see them all

![image](https://user-images.githubusercontent.com/117076/78638477-0403e800-78b5-11ea-8209-ad6a3b4bb2f2.png)

**Comment by butaji** [comment]
@legigor fixed in 1.0.1, download https://apps.apple.com/ru/app/jump-in-meeting/id1506451016?l=en&mt=12
