### ISSUE TITLE
Global shortcut conflicts with other apps

### ISSUE THREAD

**Issue by AdamSwinden** [butaji/Jump-in-Meeting#4]
Please give an option to disable and change the default Command+Shift+J shortcut as it is conflicting with and blocking the same shortcut in other apps.

**Comment by butaji** [comment]
Thanks @AdamSwinden, already on the roadmap. Just for my curiosity, what are those apps conflicting?

**Comment by AdamSwinden** [comment]
Great to hear @butaji
It’s conflicting with Xcode’s shortcut to reveal a file in the project navigator. Unfortunately it’s a shortcut I use hundreds of times a day so it means I have to quit JumpIn.

**Comment by butaji** [comment]
Got it! Thanks for sharing, now I understand your pain-point way better.

Btw, macOS widget is going to come today with the update, maybe your case, doesn’t require the app to run

**Comment by butaji** [comment]
Shortcut management added in 1.3, available in a few hours
